spring.application.name=Onskeskyen
server.port=8080
spring.thymeleaf.cache=false


spring.datasource.url=${SPRING_DEV_URL}
spring.datasource.username=${SPRING_DEV_USERNAME}
spring.datasource.password=${SPRING_DEV_PASSWORD}