# MySQL Azure connection
spring.datasource.url=jdbc:mysql://onskeskyen-db.mysql.database.azure.com:3306/onskeskyen?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=AdminLogin
spring.datasource.password=Admin1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# Server port (valgfri)
server.port=8080