spring.application.name=Onskeskyen
server.port=8081
spring.thymeleaf.cache=false
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.orm.jpa.HibernateJpaAutoConfiguration
app.database.host=localhost
app.database.port=3306
app.database.name=Onskeskyen
app.database.username=root
app.database.password=Root1234!
