spring.application.name=Onskeskyen
server.port=8081
spring.thymeleaf.cache=false
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.orm.jpa.HibernateJpaAutoConfiguration

